function bigbanglibrary(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Zb='.cache.html',$='/',Rb='1A2E34798DA0DCEA7680568594CF43B0',Tb='5B6A22BE4A821AF3EB20B6C760150694',Ub='703B122D17B804F10BBB8240718AA4C4',Yb=':',Sb=':1',nb='::',fc='<script defer="defer">bigbanglibrary.onInjectionDone(\'bigbanglibrary\')<\/script>',gb='<script id="',qb='=',Z='?',Vb='AD7274A3BFB2187A9D6DA2D2F90A8387',Wb='B95FA5CFE58F0AA01E6B2A5B5B92461B',Cb='BackCompat',sb='Bad handler "',Bb='CSS1Compat',ec='DOMContentLoaded',Xb='FA2D2DD6A1914A47EFEB2C3F967E7FBE',ib='SCRIPT',fb='__gwt_marker_bigbanglibrary',jb='base',bb='baseUrl',S='begin',P='bigbanglibrary',db='bigbanglibrary.nocache.js',mb='bigbanglibrary::',R='bootstrap',ab='clear.cache.gif',Ab='compat.mode',pb='content',X='end',Lb='gecko',Mb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',$b='gwt/standard/standard.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',dc='head',Pb='hosted.html?bigbanglibrary',cc='href',Kb='ie6',Jb='ie8',Ib='ie9',wb='iframe',_='img',xb="javascript:''",_b='link',Ob='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Hb='msie',lb='name',Eb='opera',yb='position:absolute;width:0;height:0;border:none',ac='rel',Gb='safari',cb='script',Qb='selectingPermutation',Q='startup',bc='stylesheet',eb='undefined',Nb='unknown',Db='user.agent',Fb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}bigbanglibrary=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){return document.compatMode==Bb?Bb:Cb};u[Ab]={BackCompat:0,CSS1Compat:1};v[Db]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Eb)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1}())return Gb;if(function(){return b.indexOf(Hb)!=-1&&m.documentMode>=9}())return Ib;if(function(){return b.indexOf(Hb)!=-1&&m.documentMode>=8}())return Jb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;return Nb};u[Db]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};bigbanglibrary.onScriptLoad=function(){if(H){q=true;B()}};bigbanglibrary.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Ob,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Pb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Qb});if(!A()){try{F([Cb,Eb],Rb);F([Bb,Eb],Rb);F([Cb,Eb],Rb+Sb);F([Bb,Eb],Rb+Sb);F([Cb,Gb],Tb);F([Bb,Gb],Tb);F([Cb,Gb],Tb+Sb);F([Bb,Gb],Tb+Sb);F([Cb,Ib],Ub);F([Bb,Ib],Ub);F([Cb,Ib],Ub+Sb);F([Bb,Ib],Ub+Sb);F([Cb,Jb],Vb);F([Bb,Jb],Vb);F([Cb,Jb],Vb+Sb);F([Bb,Jb],Vb+Sb);F([Cb,Kb],Wb);F([Bb,Kb],Wb);F([Cb,Kb],Wb+Sb);F([Bb,Kb],Wb+Sb);F([Cb,Mb],Xb);F([Bb,Mb],Xb);F([Cb,Mb],Xb+Sb);F([Bb,Mb],Xb+Sb);J=w[G(Ab)][G(Db)];var L=J.indexOf(Yb);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Zb}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[$b]){var a=m.createElement(_b);__gwt_stylesLoaded[$b]=a;a.setAttribute(ac,bc);a.setAttribute(cc,s+$b);m.getElementsByTagName(dc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(ec,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(ec,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Ob,millis:(new Date).getTime(),type:S});m.write(fc)}
bigbanglibrary();